import { describe, expect, it } from 'vitest';

import { and } from './and.js';
import { object } from './object.js';
import { string } from './string.js';
import { number } from './number.js';

describe('and() integration tests', () => {
  const MessageInput = object({
    name: 'MessageInput',
    shape: {
      text: string(),
    },
  });

  const WithId = object({
    name: 'WithId',
    shape: {
      id: string(),
    },
  });

  const WithTimestamp = object({
    name: 'WithTimestamp',
    shape: {
      timestamp: number(),
    },
  });

  describe('legacy API', () => {
    it('should compose two schemas with left/right', () => {
      const MessageWithId = and({
        left: MessageInput,
        right: WithId,
        name: 'MessageWithId',
      });

      const result = MessageWithId.parse({ text: 'Hello', id: 'm-1' });
      expect(result).toEqual({ text: 'Hello', id: 'm-1' });
      expect(MessageWithId.name).toBe('MessageWithId');
    });
  });

  describe('new API with schemas array', () => {
    it('should compose two schemas', () => {
      const schemas = [MessageInput, WithId] as const;
      const MessageWithId = and({
        name: 'MessageWithId',
        schemas,
      });

      const result = MessageWithId.parse({ text: 'Hello', id: 'm-2' });
      expect(result).toEqual({ text: 'Hello', id: 'm-2' });
      expect(MessageWithId.name).toBe('MessageWithId');
    });

    it('should compose three schemas', () => {
      const schemas = [MessageInput, WithId, WithTimestamp] as const;
      const MessageComplete = and({
        name: 'MessageComplete',
        schemas,
      });

      const result = MessageComplete.parse({
        text: 'Hello',
        id: 'm-3',
        timestamp: 123456,
      });
      expect(result).toEqual({
        text: 'Hello',
        id: 'm-3',
        timestamp: 123456,
      });
      expect(MessageComplete.name).toBe('MessageComplete');
    });

    it('should use auto-generated name when name is not provided', () => {
      const schemas = [MessageInput, WithId] as const;
      const MessageWithId = and({ schemas });

      const result = MessageWithId.parse({ text: 'Hello', id: 'm-4' });
      expect(result).toEqual({ text: 'Hello', id: 'm-4' });
      // Name should be auto-generated by chaining
      expect(MessageWithId.name).toContain('MessageInput');
    });
  });
});
